services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rehsozEvilDeedz
      MYSQL_DATABASE: safana_db
      MYSQL_USER: virtuosa
      MYSQL_PASSWORD: cello
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  safana-bekam-api:
    build:
      context: .
    container_name: safana-bekam-api
    environment:
      DATABASE_URI: "mysql+pymysql://virtuosa:cello@mariadb:3306/safana_db"
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    volumes:
      - .:/safana-bekam-api
    command: ["/safana-bekam-api/entrypoint.sh"]

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-safana
    ports:
      - "5001:80"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      # PMA_USER: virtuosa
      # PMA_PASSWORD: cello
