version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rehsozEvilDeedz
      MYSQL_DATABASE: safana_db
      MYSQL_USER: rehsoz
      MYSQL_PASSWORD: beanz
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  safana-bekam-api:
    build:
      context: .
    container_name: safana-bekam-api
    environment:
      DATABASE_URI: "mysql+pymysql://rehsoz:beanz@mariadb:3306/safana_db"
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    volumes:
      - .:/safana-bekam-api
    command: ["/safana-bekam-api/entrypoint.sh"]

